use utoipa::OpenApi;

use super::routes::{
    agents, application, backtest, bots, config, exchanges, health, meta, monitor, orders,
    portfolio, providers, strategy,
};
use crate::modules::application_contracts::Signal;
use crate::modules::config_api::{OperationMode, RiskProfile, RunMode};
use crate::modules::exchanges::capabilities::{Capability, ExchangeCapability};
use crate::modules::http_bridge::{
    agents as agents_bridge, application as application_bridge, backtest as backtest_bridge,
    bots as bots_bridge, config as config_bridge, exchanges as exchanges_bridge,
    orders as orders_bridge, portfolio as portfolio_bridge, providers as providers_bridge, risk,
    strategy as strategy_bridge,
};
use crate::modules::market::models::Candle;
use crate::presentation::http::error::ApiErrorBody;

#[derive(OpenApi)]
#[openapi(
    paths(
        health::healthz,
        health::readyz,
        meta::meta,
        application::list_signals,
        config::config_active,
        config::config_snapshot,
        providers::provider_status,
        exchanges::catalog,
        exchanges::routing_matrix,
        bots::bot_catalog,
        bots::bot_ranking,
        agents::list_agents,
        agents::register_agent,
        agents::audit_log,
        agents::get_agent,
        agents::pause_agent,
        agents::resume_agent,
        agents::retire_agent,
        agents::run_advisory,
        crate::presentation::http::routes::risk::compute_profile_limits,
        crate::presentation::http::routes::risk::validate_order_intent,
        crate::presentation::http::routes::risk::gate_signal,
        strategy::sma_periods,
        strategy::evaluate_sma,
        portfolio::paper_wallet,
        backtest::run_sma_backtest,
        orders::submit_order,
        monitor::snapshot,
        monitor::post_command,
    ),
    components(schemas(
        ApiErrorBody,
        health::HealthResponse,
        health::ReadyResponse,
        meta::MetaResponse,
        application_bridge::SignalDescriptor,
        application_bridge::SignalsResponse,
        Signal,
        config_bridge::ConfigSnapshotQuery,
        config_bridge::ConfigSnapshotResponse,
        providers_bridge::ProvidersStatusResponse,
        exchanges_bridge::ExchangeCatalogResponse,
        exchanges_bridge::ExchangeRoutingResponse,
        exchanges_bridge::RoutingRow,
        ExchangeCapability,
        Capability,
        agents_bridge::AgencyQuery,
        agents_bridge::RegisterAgentRequest,
        agents_bridge::AgentRoleBody,
        agents_bridge::SupervisorRefBody,
        agents_bridge::AgentResponse,
        agents_bridge::AgentListResponse,
        agents_bridge::AuditLogResponse,
        agents_bridge::AuditEventResponse,
        agents_bridge::LifecycleResponse,
        agents_bridge::AdvisoryRequest,
        agents_bridge::AdvisoryResponse,
        risk::ProfileLimitsRequest,
        risk::ProfileLimitsResponse,
        risk::ValidateIntentRequest,
        risk::ValidateIntentResponse,
        risk::RiskLimitsBody,
        risk::OrderIntentBody,
        risk::GateSignalRequest,
        risk::GateSignalResponse,
        RiskProfile,
        RunMode,
        strategy_bridge::StrategyPeriodsResponse,
        strategy_bridge::PeriodsQuery,
        strategy_bridge::EvaluateSmaRequest,
        strategy_bridge::EvaluateSmaResponse,
        Candle,
        OperationMode,
        portfolio_bridge::PaperSnapshotResponse,
        portfolio_bridge::PaperSnapshotQuery,
        bots_bridge::BotCatalogResponse,
        bots_bridge::BotCatalogEntry,
        orders_bridge::SubmitOrderHttpRequest,
        orders_bridge::SubmitOrderResponse,
        orders_bridge::OrderSideBody,
        backtest_bridge::BacktestRequest,
        crate::modules::http_bridge::monitor::MonitorSnapshotResponse,
        crate::modules::http_bridge::monitor::MonitorCommandRequest,
        crate::modules::http_bridge::monitor::MonitorCommandResponse,
        crate::modules::http_bridge::monitor::MonitorCommandName,
    )),
    tags(
        (name = "system", description = "Health and metadata"),
        (name = "application", description = "Shared application contracts"),
        (name = "config", description = "Read-only configuration snapshots"),
        (name = "providers", description = "External provider configuration flags"),
        (name = "agents", description = "Identity-only agent registry and lifecycle"),
        (name = "exchanges", description = "Exchange catalog and routing"),
        (name = "risk", description = "Risk limits and validation"),
        (name = "strategy", description = "Strategy presets and evaluation"),
        (name = "portfolio", description = "Paper portfolio snapshots"),
        (name = "bots", description = "Bot catalog from active config"),
        (name = "orders", description = "Order intent submission (fail-closed execution)"),
        (name = "backtest", description = "Synthetic SMA backtest"),
        (name = "monitor", description = "Live monitor control when attached"),
    ),
    info(
        title = "Rust Trading Bot API",
        version = "0.1.0",
        description = "HTTP surface for backend modules. Monitor routes require a monitor handle in the same process; Jev advisory requires jev.enabled and API credentials."
    )
)]
pub struct ApiDoc;
